{% set name = "libhxl" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2462d3828a57e2ad39484d60773f3f94890fbb183c75309e058e17e7269f563d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hxladd = hxl.scripts:hxladd
    - hxlappend = hxl.scripts:hxlappend
    - hxlclean = hxl.scripts:hxlclean
    - hxlcount = hxl.scripts:hxlcount
    - hxlcut = hxl.scripts:hxlcut
    - hxldedup = hxl.scripts:hxldedup
    - hxlexpand = hxl.scripts:hxlexpand
    - hxlexplode = hxl.scripts:hxlexplode
    - hxlfill = hxl.scripts:hxlfill
    - hxlimplode = hxl.scripts:hxlimplode
    - hxlhash = hxl.scripts:hxlhash
    - hxlmerge = hxl.scripts:hxlmerge
    - hxlrename = hxl.scripts:hxlrename
    - hxlreplace = hxl.scripts:hxlreplace
    - hxlselect = hxl.scripts:hxlselect
    - hxlsort = hxl.scripts:hxlsort
    - hxlspec = hxl.scripts:hxlspec
    - hxltag = hxl.scripts:hxltag
    - hxlvalidate = hxl.scripts:hxlvalidate

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonpath-ng
    - ply
    - pytest
    - python-dateutil
    - python-io-wrapper
    - requests >=2.11
    - requests_cache
    - structlog ==22.1.0
    - unidecode
    - urllib3 <1.27,>=1.21.1
    - xlrd3 ==1.1.0

test:
  imports:
    - hxl
    - hxl.formulas
  requires:
    - pip
  commands:
    - pip check
    - hxladd -h
    - hxlappend -h
    - hxlclean -h
    - hxlcount -h
    - hxlcut -h
    - hxldedup -h
    - hxlexpand -h
    - hxlexplode -h
    - hxlfill -h
    - hxlimplode -h
    - hxlhash -h
    - hxlmerge -h
    - hxlrename -h
    - hxlreplace -h
    - hxlselect -h
    - hxlsort -h
    - hxlspec -h
    - hxltag -h
    - hxlvalidate -h

about:
  home: http://hxlstandard.org
  summary: Python support library for the Humanitarian Exchange Language (HXL)
  description: |
    This library provides support for parsing, validating, cleaning, and
    transforming humanitarian datasets that follow the
    [HXL standard](https://hxlstandard.org). Its use will be familiar to
    developers who have worked with libraries like [JQuery](https://jquery.com).
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE.md
  doc_url: https://hxlstandard.github.io/libhxl-python/
  dev_url: https://github.com/HXLStandard/libhxl-python

extra:
  recipe-maintainers:
    - kynan
